---
title: "Pine Martens Study Area 3"
author: "Clara Panchaud"
date: "2023-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(dplyr)
library(ggplot2)
library(secr)
library(sf)
Rcpp::sourceCpp("/Users/clara/Documents/RProjects/SECR_memory/LikelihoodC.cpp")
source("/Users/clara/Documents/RProjects/SECR_memory/Sim_Func.R")
source("/Users/clara/Documents/RProjects/SECR_memory/Fit_Func.R")
```
Load the data

```{r}
data<-read.csv("/Users/clara/Documents/RProjects/Pine_Martens/Data analysis/pine_martens.csv")
traps<-read.csv("/Users/clara/Documents/RProjects/Pine_Martens/Data analysis/CameraLocations.csv")
```
We focus on data from the 2017 season, so we only keep this data. 
We remove the data that has a field season NA (this is data was collected in december 2017 and january 2018) 
```{r}
remove<-which(is.na(data$FieldSeason))
data<-data[-remove,]
data<-data[data$FieldSeason==2017,] 
data<-data[data$IndividualID!=0,] # remove the unmarked individuals
data
```




```{r}
remove<-which(is.na(traps$FieldSeason))
traps<-traps[-remove,]
traps<-traps[traps$FieldSeason==2017,]
```


```{r}
data3<-data[data$StudyAreaID==3,]
data3
traps3<- subset(traps, StudyAreaID==3)
```





```{r}

date_obs<-mdy(gsub("/","-",data3$DefaultStart))
start_date<-rep(ymd(20170227),length(date_obs))
day_obs<-as.numeric(date_obs-start_date)

time<-hms(data3$StartTime)
hours<-hour(time)
minutes<-minute(time)
data3$Time<-round(day_obs+(hours*60+minutes)/1440,digits=3)
```


```{r}
df3 <- subset(data3, select = c(IndividualID,Time,LocationID))
traps3<-subset(traps3, select = c(LocationID,UTM_E,UTM_N))
colnames(df3)<-c("id","Time","y")
rownames(traps3)<-traps3$LocationID
traps3<- subset(traps3, select = c(UTM_E,UTM_N))
colnames(traps3)<-c("x","y")

unique_ids<-unique(df3$id)
df3$id<-match(df3$id,unique_ids)
df3<-df3[order(df3$id,df3$Time),]

traps3$x<-traps3$x/1000
traps3$y<-traps3$y/1000

traps3$name<-rownames(traps3)
unique_traps<-unique(traps3$name)
df3$y<-match(df3$y,unique_traps)
rownames(traps3)<-c(1:30)
traps3<-subset(traps3, select = c(x,y))
```

Buffers were tested "by hand" until estimated parameters values were stable. Which was achieved with a buffer of 2. 

```{r}
df3
```


```{r}
trap3 = make.poly(x=traps3$x, y=traps3$y)
mask3 = make.mask(trap3,buffer=2,spacing=0.2,type="trapbuffer")
thinmask3<-make.mask(trap3,buffer=2,spacing=0.05,type="trapbuffer")
thinmeshmat3<-as.matrix(thinmask3)
meshmat3<-as.matrix(mask3)
plot(meshmat3,)
points(trap3,col="red",pch=19)


plot(mask3,dots=FALSE,border=0,xlim=c(310,325),ylim=ylim,ppoly=FALSE,asp=1)
plotMaskEdge(mask3,add=TRUE)
points(trap3,pch=18)
title("Study Area")
legend_label <- "Camera Traps"
legend("topright", legend = legend_label, pch = 18, col = "black", cex = 0.8, inset = c(0.12,0.12))
```


```{r}
K<-30
T<-12
r2<-100
```

```{r}
ddf3 <- data.frame(t = as.numeric(), y = as.integer(), id = as.integer())

for(i in unique(df3$id)){
    data <- discretize(df3[df3$id == i, ],T, r2)
    data$id <- i
    ddf3 <- rbind(ddf3, data)
  }
ddfmat3 = as.matrix(ddf3)
dfrows3 = as.numeric(table(ddf3$id))

n3<-length(unique(ddf3$id))
trap3<-as.matrix(traps3)
```

```{r}
theta<-c(1.5,-2,1.2) # h0, sigma, beta
traps3<-as.matrix(traps3)
LikelihoodC(theta = theta, trap = traps3, df = ddfmat3, dfrows = dfrows3, mesh = meshmat3, endt = T)
```

After some tests it seems like spacing at 0.2 and r=100 is a good compromise


```{r}
theta<-c(1.5,-2,1.3)
```


```{r}
start_time <- Sys.time()
fit3 <- optim(theta, LikelihoodC, trap = traps3, df = ddfmat3, dfrows = dfrows3, mesh = meshmat3, endt = T,hessian=TRUE) 
end_time <- Sys.time()
end_time - start_time

theta_est<-fit3$par
```

```{r}
param<-confint_param(fit3,T,traps3,mask3,n3)
N_est<-confint_pop(fit3,T,traps3,mask3,n3,distribution = "poisson", loginterval = TRUE, alpha = 0.05)
param
N_est
```



```{r}
theta<-c(1.5,-2) 

start_time <- Sys.time()
fit_nomem3 <- optim(theta, LikelihoodCnoMem, trap = traps3, df = ddfmat3, dfrows = dfrows3, mesh = meshmat3, endt = T,hessian=TRUE) 
end_time <- Sys.time()
end_time - start_time

param_nm<-confint_param(fit_nomem3,T,traps3,mask3,n3)
N_nm<-confint_pop(fit_nomem3,T,traps3,mask3,n3,distribution = "poisson", loginterval = TRUE, alpha = 0.05)
```

-0.3617807	0.2238675	-0.947429		
-1.9906776	-1.5565037	-2.424852		

22.90404	


The AIC difference
```{r}
theta_est_nomem<-fit_nomem3$par
(2*fit_nomem3$value-2*2)-(2*fit3$value - 2*3)
```
35.88383



