---
title: "AC_OU"
author: "Clara Panchaud"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(dplyr)
library(ggplot2)
library(secr)
library(sf)
Rcpp::sourceCpp("/Users/clara/Documents/RProjects/SECR_memory/LikelihoodC.cpp")
source("/Users/clara/Documents/RProjects/SECR_memory/Sim_Func.R")
source("/Users/clara/Documents/RProjects/SECR_memory/Fit_Func.R")
```

```{r}
traps<-read.csv("/Users/clara/Documents/RProjects/Pine_Martens/Data analysis/pine_marten_traps.csv",row.names=1)

df<-read.csv("/Users/clara/Documents/RProjects/Pine_Martens/Simulation_OU/df_01.csv",row.names=1)

fit <- get(load("/Users/clara/Documents/RProjects/Pine_Martens/Simulation_OU/model_1.Rdata"))
                
fit_nomem <- get(load("/Users/clara/Documents/RProjects/Pine_Martens/Simulation_OU/model_nm_1.Rdata"))

theta_est<-fit$par
theta_est_nm<-fit_nomem$par
```


 315.3644 4965.385


315.7417	4964.331		
316.1591	4965.364		
315.7518	4966.062	
```{r}
trap_poly
```


```{r}
space=0.05
trap_mat<-as.matrix(traps)
trap_poly = make.poly(x=traps$x, y=traps$y)
mask = make.mask(trap_poly,buffer=2,spacing=space,type="trapbuffer")
meshmat<-as.matrix(mask)

```

```{r}

data<-df[df$id==1,]
trap_ind<-data.frame( x = trap_poly$x, y = trap_poly$y, seen = rep(0,31),seen_indic=rep(0,31))
for ( i in 1:length(table(data$y))){
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen<-table(data$y)[i]
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen_indic<-1
}

data<-discretize(data,12,10)
ac_posterior_ind<-apply(meshmat,1,Likelihood_ind,theta=theta_est,trap=trap_poly,data=data,memory=1)
integral<-as.double(exp(Likelihood_integrate(theta_est,trap_poly,data,mask,1)))

ac_density_ind<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind)/integral)
colnames(ac_density_ind)<-c("x","y","value")

fill_seen_zero <- "white"
plot_ind<- ggplot(ac_density_ind, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,318))+
  ylim(c(4961,4970))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =  315.364, yaxis =4965.385), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind


```

```{r}
ac_posterior_ind_nm<-apply(meshmat,1,Likelihood_ind,theta=theta_est_nm,trap=trap_poly,data=data,memory=0)
integral_nm<-as.double(exp(Likelihood_integrate(theta_est_nm,trap_poly,data,mask,0)))
ac_density_ind_nm<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind_nm)/integral_nm)
colnames(ac_density_ind_nm)<-c("x","y","value")


fill_seen_zero <- "white"
plot_ind_nm<- ggplot(ac_density_ind_nm, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,318))+
  ylim(c(4961,4970))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =  315.364, yaxis =4965.385), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind_nm

```





```{r}

data<-df[df$id==2,]
trap_ind<-data.frame( x = trap_poly$x, y = trap_poly$y, seen = rep(0,31),seen_indic=rep(0,31))
for ( i in 1:length(table(data$y))){
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen<-table(data$y)[i]
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen_indic<-1
}

data<-discretize(data,12,10)
ac_posterior_ind2<-apply(meshmat,1,Likelihood_ind,theta=theta_est,trap=trap_poly,data=data,memory=1)
integral2<-as.double(exp(Likelihood_integrate(theta_est,trap_poly,data,mask,1)))

ac_density_ind2<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind2)/integral2)
colnames(ac_density_ind2)<-c("x","y","value")

fill_seen_zero <- "white"
plot_ind2<- ggplot(ac_density_ind2, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,317))+
  ylim(c(4955,4960))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =  314.2144 , yaxis =4957.535), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind2


```


```{r}
ac_posterior_ind_nm2<-apply(meshmat,1,Likelihood_ind,theta=theta_est_nm,trap=trap_poly,data=data,memory=0)
integral_nm2<-as.double(exp(Likelihood_integrate(theta_est_nm,trap_poly,data,mask,0)))
ac_density_ind_nm2<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind_nm2)/integral_nm2)
colnames(ac_density_ind_nm2)<-c("x","y","value")


fill_seen_zero <- "white"
plot_ind2<- ggplot(ac_density_ind_nm2, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,317))+
  ylim(c(4955,4960))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =   314.2144 , yaxis =4957.535), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind2

```


```{r}
data<-df[df$id==3,]
trap_ind<-data.frame( x = trap_poly$x, y = trap_poly$y, seen = rep(0,31),seen_indic=rep(0,31))
for ( i in 1:length(table(data$y))){
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen<-table(data$y)[i]
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen_indic<-1
}

data<-discretize(data,12,10)
ac_posterior_ind<-apply(meshmat,1,Likelihood_ind,theta=theta_est,trap=trap_poly,data=data,memory=1)
integral<-as.double(exp(Likelihood_integrate(theta_est,trap_poly,data,mask,1)))

ac_density_ind<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind)/integral)
colnames(ac_density_ind)<-c("x","y","value")

fill_seen_zero <- "white"
plot_ind<- ggplot(ac_density_ind, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,318))+
  ylim(c(4960,4965))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =  314.0644, yaxis =4962.585), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind
```

```{r}
data<-df[df$id==3,]
trap_ind<-data.frame( x = trap_poly$x, y = trap_poly$y, seen = rep(0,31),seen_indic=rep(0,31))
for ( i in 1:length(table(data$y))){
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen<-table(data$y)[i]
  trap_ind[as.numeric(names(table(data$y))[i]),]$seen_indic<-1
}

data<-discretize(data,12,10)
ac_posterior_ind_nm<-apply(meshmat,1,Likelihood_ind,theta=theta_est_nm,trap=trap_poly,data=data,memory=0)
integral_nm<-as.double(exp(Likelihood_integrate(theta_est_nm,trap_poly,data,mask,0)))

ac_density_ind_nm<-data.frame(meshmat[,1],meshmat[,2],unlist(ac_posterior_ind_nm)/integral_nm)
colnames(ac_density_ind_nm)<-c("x","y","value")

fill_seen_zero <- "white"
plot_ind<- ggplot(ac_density_ind_nm, aes(x = x, y = y, fill = value) ) +   
  geom_raster() +
  coord_fixed() +
  xlim(c(312,318))+
  ylim(c(4960,4965))+
  scale_fill_gradient(low = "white", high = "black", name = "AC PDF") +
  scale_color_grey(name = "") + 
  ggtitle("") +
  geom_point(data = trap_ind, aes(x = x, y = y,size=as.factor(seen)), shape=23,fill = ifelse(trap_ind$seen == 0, fill_seen_zero, "grey"), color="black", inherit.aes = FALSE)+
  labs(fill = "Hazard value", size= "Number of captures",) +
  geom_point(data = data.frame(xaxis =  314.0644, yaxis =4962.585), aes(x = xaxis, y = yaxis,color="activity centre") ,size=4,inherit.aes = FALSE)+
  scale_size_discrete(range = c(5, 10))
plot_ind
```
            x        y
26517 315.3644 4965.385
10323 314.2144 4957.535

20723 314.0644 4962.585


17464 315.9144 4960.985
14845 313.7144 4959.735
9317  315.4144 4957.035
21074 316.1644 4962.735
18683 315.0644 4961.585
19542 316.8144 4961.985
26975 317.6644 4965.585
22011 316.6644 4963.185
28082 316.3644 4966.135
21582 315.8144 4962.985
16745 316.0144 4960.635
14548 314.3144 4959.585
26715 314.9644 4965.485
2354  317.4644 4953.635
12389 314.5144 4958.535
19486 314.0144 4961.985
18063 314.9644 4961.285
30337 315.8144 4967.235
13054 316.8644 4958.835
22496 315.1644 4963.435
16356 317.1644 4960.435
28909 316.5144 4966.535
8303  316.2144 4956.535
4273  315.5644 4954.585
29732 316.4644 4966.935
3547  315.3144 4954.235
23197 314.1644 4963.785
19992 313.5644 4962.235
24352 315.2644 4964.335
10146 315.6644 4957.435
12382 314.1644 4958.535
2975  317.6144 4953.935
17559 315.5144 4961.035
30247 316.4644 4967.185
16672 317.5144 4960.585
25642 317.9644 4964.935
26569 317.9644 4965.385
11183 316.0144 4957.935
28074 315.9644 4966.135
21607 317.0644 4962.985
25543 318.1644 4964.885
20789 317.3644 4962.585
21497 316.7144 4962.935
14231 313.9144 4959.435
24397 317.5144 4964.335
16038 316.7144 4960.285
23837 315.2644 4964.085
9017  315.8644 4956.885
15946 317.2644 4960.235
28366 315.1144 4966.285
30733 315.0144 4967.435
12816 315.2644 4958.735
16981 317.5144 4960.735
27047 316.1144 4965.635
15198 315.9144 4959.885
21670 315.0644 4963.035
14862 314.5644 4959.735
12318 316.1144 4958.485
23140 316.4644 4963.735
16455 316.9644 4960.485
2334  316.4644 4953.635
21860 314.2644 4963.135
12683 313.7644 4958.685
15750 317.7644 4960.135
18433 318.0144 4961.435
25321 317.3644 4964.785
2114  315.7644 4953.535
21200 317.3144 4962.785
22894 314.4644 4963.635
12084 314.7144 4958.385
10471 316.4644 4957.585
10643 314.7644 4957.685
5003  316.0144 4954.935
16005 315.0644 4960.285
12274 313.9144 4958.485
9223  315.8644 4956.985
3854  315.2144 4954.385
1632  317.4144 4953.285
19199 315.1144 4961.835
12536 316.7144 4958.585
23758 316.4644 4964.035
25691 315.2644 4964.985
22937 316.6144 4963.635
18573 314.7144 4961.535
24511 318.0644 4964.385
12820 315.4644 4958.735
13629 314.7144 4959.135
8818  316.2144 4956.785
276   316.5644 4952.635
19038 317.3644 4961.735
4267  315.2644 4954.585
10498 317.8144 4957.585
28165 315.3644 4966.185
21619 317.6644 4962.985
29187 314.9644 4966.685
28496 316.4644 4966.335
9520  315.2644 4957.135

